extends:
  - spectral:oas

rules:
  # Basic OpenAPI 3.0/3.1 validation
  oas3-api-servers: warn
  oas3-valid-schema-example: warn
  oas3-valid-media-example: warn
  # Disable oas3-schema due to false positives with $ref in OpenAPI 3.1 path items
  # This is a known issue: https://github.com/stoplightio/spectral/issues/2224
  oas3-schema: off
